docs: ✏️ Securing a node with SSL/TLS
fleek-network/fleek-network-docs pull request #9
Opened 2023-01-24 18:04 UTC by heldrida

2023-01-25 20:31 UTC, ozwaldorf requested changes

2023-01-25 20:31 UTC, ozwaldorf commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +There are plenty of free domain server providers but for this guide will opt for [Ngrok](https://ngrok.com), there are other alternatives such as [Localhost.run](localhost.run) or [LocalTunnel.me](ht
```suggestion
There are plenty of free domain server providers, but for this guide we will opt for [Ngrok](https://ngrok.com). There are other alternatives such as [Localhost.run](localhost.run) or [LocalTunnel.me](https://localtunnel.me), but we're keeping things simple here and will not try to provide support for anything else. Using an alternative should be quite similar! 
```

2023-01-25 20:31 UTC, ozwaldorf commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +
hmm doesn't seem to have the ip address in the example response

2023-01-25 20:31 UTC, ozwaldorf commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +
```suggestion

> Note: if multiple domain names are used, the `init-letsencrypt.sh` script will export them under the first domain provided

```

2023-01-25 20:31 UTC, ozwaldorf commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +```
Maybe this bit of info could be better put farther above where the chmod +x is done

2023-01-25 20:31 UTC, ozwaldorf commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +
for redundancy:
```suggestion

> Note: if multiple domains are provided, the certificates will be stored under the first one

```

2023-01-25 20:31 UTC, ozwaldorf commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +You may also find that the paragraph after, that mentions that the certificate expires is important. If you are running the Docker Stack we provide, the `certbot` is installed and automating the cert
```suggestion
You may also find that the paragraph after, that mentions that the certificate expires is important. If you are running the Docker Stack we provide, the `certbot` is installed and automates renewing the certification for you.
```

2023-01-25 21:28 UTC, theBeardA commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +The knowledge demonstrated here should be useful and can be easily applied to native setups (none Docker). As some troubleshooting and differences are found in different systems, we'll stick with our
```suggestion
The knowledge demonstrated here should be useful and can be easily applied to native setups (not Docker). As some troubleshooting and differences are found in different systems, we'll stick with our Docker Stack for that matter and simplicity!
```

the `none` doesn't sound right here 🤔

2023-01-25 21:57 UTC, nicolaspoggi requested changes
Solid write! Can't validate technically fully - but the guide is clear, left a minor suggestion, and then one more global suggestion is reducing the use of "!" to end sentences which in this case stood out.

2023-01-25 21:57 UTC, nicolaspoggi commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +### Alternatively, getting a free domain name for testing?
```suggestion
### Alternatively, how can one get a free domain name for testing?
```

2023-01-26 11:47 UTC, heldrida commented on guides/Network nodes/fleek-network-securing-a-node-with-ssl-tls.md
> +💡 Generally referred to as SSL, or TLS (Transport Layer Security), the modern version that's usually named SSL)
Done

2023-01-26 15:04 UTC, ozwaldorf approved these changes

2023-01-26 15:10 UTC, merged